// <auto-generated />
namespace EasyCredit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mora_1_30 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mora_1_30));
        
        string IMigrationMetadata.Id
        {
            get { return "202206211724173_mora_1_30"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
