//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyCredit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanAccount
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int TypeTransId { get; set; }
        public decimal RequiredAmount { get; set; }
        public int PayMethodeId { get; set; }
        public Nullable<int> IdWarranty { get; set; }
        public Nullable<int> IdWarrant { get; set; }
        public int CuotesQuantity { get; set; }
        public decimal CuotesAmount { get; set; }
        public decimal MonthlyInterest { get; set; }
        public System.DateTime RequirementDate { get; set; }
        public System.DateTime AproveDate { get; set; }
        public System.DateTime InitialPayDate { get; set; }
        public System.DateTime FinalPayDate { get; set; }
        public string RegisteredBy { get; set; }
        public int Aprobacion { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Clients Clients1 { get; set; }
        public virtual Warranty Warranty { get; set; }
        public virtual PayMethodes PayMethodes { get; set; }
        public virtual TypeTransaction TypeTransaction { get; set; }
        //public virtual Transactions Transactions { get; set; }
    }
}
