//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyCredit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Transactions
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int TypeTransId { get; set; }
        public decimal TransactionAmount { get; set; }
        public int PayMethodeId { get; set; }
        public System.DateTime DepositDate { get; set; }
        public string RegisteredBy { get; set; }
        public Nullable<decimal> nivel_mora { get; set; }
        [Display(Name = "Intereses-Mora")]
        public Nullable<decimal> mora { get; set; }
        public Nullable<int> LoanId { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual PayMethodes PayMethodes { get; set; }
        public virtual TypeTransaction TypeTransaction { get; set; }
    }
}
